### ISSUE TITLE
SyntaxError 

### ISSUE THREAD

**Issue by BDadmehr0** [DataWaveProject/nonlocal_gwfluxes#4]
```
ERROR: Failed on file: ./quick_inference_script/two_sample_inference.py
Traceback (most recent call last):
  File "/home/dadmehr/.local/bin/pipreqs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 609, in main
    init(args)
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 533, in init
    candidates = get_all_imports(
                 ^^^^^^^^^^^^^^^^
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 153, in get_all_imports
    raise exc
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 139, in get_all_imports
    tree = ast.parse(contents)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 90
    out=f{model}+'_output.npz'
         ^
SyntaxError: invalid syntax

```

**Comment by BDadmehr0** [comment]
https://github.com/DataWaveProject/nonlocal_gwfluxes/pull/5

**Comment by BDadmehr0** [comment]
```
ERROR: Failed on file: ./attention_unet/inference_ifs.py
Traceback (most recent call last):
  File "/home/dadmehr/.local/bin/pipreqs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 609, in main
    init(args)
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 533, in init
    candidates = get_all_imports(
                 ^^^^^^^^^^^^^^^^
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 153, in get_all_imports
    raise exc
  File "/home/dadmehr/.local/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 139, in get_all_imports
    tree = ast.parse(contents)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 93
    elif:
        ^
SyntaxError: invalid syntax

```
